---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

platform:
  os: linux
  arch: amd64

steps:
  - name: build_site
    image: iotapi322/docs:latest
    commands:
      - mkdocs build
      - echo "Hello build"

  - name: deploy_site
    image: appleboy/drone-scp
    settings:
      host: dockerhost
      user: snoby
      port: 22
      key:
        from_secret: SSH_KEY
      target: /mnt/data/docs/
      source: site
      rm: true
    when:
      branch: master

  - name: "restart nginx"
    image: appleboy/drone-ssh
    settings:
      host: dockerhost
      user: snoby
      port: 22
      key:
        from_secret: SSH_KEY
      script:
        - /home/snoby/docker_start_up_commands/docs/run_docs.sh
    when:
      branch: master
