site_name: Snoby Home Document Service
site_description: "Information about the home lab and home network"
site_author: "Matt Snoby"
site_url: "http://docs.mattsnoby.com"
nav:
  - Home: index.md
  - Lab:
      - Drone: drone.md
      - Molecule: molecule.md
      - Mellanox: mellanox.md
      - R720: r720.md
      - Bonding: bonding.md
      - SR-IOV: vfs.md
  - House Information:
      - Upstairs: rooms/upstairs.md
      - Downstairs: rooms/downstairs.md
      - Basement: rooms/basement.md
      - Electrical: rooms/electrical.md
theme:
  name: material
  language: "en"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integration
    - search.suggest

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.critic

extra_css:
  - extra.css

plugins:
  - search:
      lang: en
  - img2fig

extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js

repo_url: https://github.com/snoby/home_docs/
repo_name: github.com/snoby/home_docs
edit_uri: blob/master/home_docs/
extra:
  generator: false
