# Project information
site_name: 'Snoby home network'
site_description: 'Information about the home lab and home network'
site_author: 'Matt Snoby'
site_url: 'https://info.mattsnoby.com'
nav:
  - Home: index.md
  - About: about.md
  - Mellanox: mellanox.md
  - Dell: r720.md

markdown_extensions:
  - meta
  - toc:
     permalink: True
  - attr_list

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
  - navigation.instant
  - navigation.expand
  - navigation.sections
  - toc.integration
